#!/bin/sh

echo -n $0: 'End of sentence 3... '

cat >test.in <<'eof'
"I... really don't know."
eof

cat >test.ref <<eof
No phrases in 1 sentence found.
eof

sh ./test/rundiction test.in >test.data

if cmp test.ref test.data
then
  rm -f test.*
  echo passed
else
  echo failed
  exit 1
fi
